export const jobsList = {
  'Institute of Advanced Analytics, NC State University': [
    {
      position: 'M.S. Candidate in Analytics',
      timeline: '06/2022 - 05/2023',
      responsibilities: [
        'Cover various statistical concepts such as linear regression, logistic regression, time series, text analysis, and machine learning.',
        'Conduct network and sentiment analysis on two years of social media forum text data.',
        'Build machine learning models using Python to predict forum thread length and duration based on entities and user interaction.',
        'Develop dynamic visualizations in open-source software to clearly communicate results.'
      ]
    }
  ],
  'RTI International': [
    {
      position: 'Software Developer',
      timeline: '01/2020 - 06/2022',
      responsibilities: [
        'Working with teams of data scientists, statisticians, and researchers to develop and maintain web-based applications for data visualization using Python and Vue.js.',
        'Using Python to process data for use in visualizations.',
        'Updating front-end, back-end, database, and extract, transform, load (ETL) components to meet client requests for a project designed to aggregate 911 call data.',
        'Adding new features to Myalgic Encephalomyelitis/Chronic Fatigue Syndrome web application (mapMECFS), designed to provide a dynamic, searchable interface to a comprehensive set of experimental results generated by ME/CFS Network'
      ]
    },
    {
      position: 'Software Developer',
      timeline: 'Continued',
      responsibilities: [
        'Created a web application to search, sort, and filter Belize-based non-govermental organization (NGO) data.',
        'Worked on a dashboard prototype that build upon the original National Victimization Analysis Tool (NVAT) to create a next generation interactive and visual tool to explore the NCVS data.',
        'Contributing features to internal data visualization library that allows for the easy creation of data visualization dashboards.'
      ]
    }
  ],
  'Consultants to Government and Industry (CGI)': [
    {
      position: 'Software Developer',
      timeline: '02/2019 - 01/2020',
      responsibilities: [
        'Used Python and Kafka to parse JSON messages containing health care claim information.',
        'Created Python unit test framework for parser program.',
        'Supported legacy Java application for transmitting health insurance claim images.'
      ]
    },
    {
      position: 'Software Developer Intern',
      timeline: '06/2018 - 07/2018',
      responsibilities: [
        'Worked with 7 interns located in 4 different cities.',
        'Held 2 separate roles over 2 sprints: Developer and Technical Lead.',
        [
          'Created a web application which tracks meeting attendees, project health, project and meeting scorecards, and the current project reviewer for engineering review meetings.'
        ]
      ]
    }
  ],
  'University of North Carolina at Charlotte': [
    {
      position: 'Client Support Tech Asst II',
      timeline: '09/2017 - 12/2018',
      responsibilities: [
        'Provided support to lower level Technical Assistants.',
        'Maintained working knowledge of common issues that arise in the Information Technology Service Desk.',
        'Assisted faculty and students in resolving technical issues ranging from password resets to network issues.',
        'Communicated solutions and processes so that customers will be better equipped to deal with problems in the future.'
      ]
    },
    {
      position: 'Client Support Tech Asst I',
      timeline: '11/2016 - 09/2017',
      responsibilities: [
        'Assisted faculty and students in resolving technical issues ranging from password resets to network issues.',
        'Communicated solutions and processes so that customers will be better equipped to deal with problems in the future.'
      ]
    }
  ],
  'United States Marine Corps': [
    {
      position: 'Public Affairs Liaison (Sergeant / E5)',
      timeline: '08/2013 - 10/2014',
      responsibilities: [
        'Organized and coordinated public events with outside agencies for 200 Marines.',
        'Supervised Marine Corps tasks issued to groups of 4, 12, 50, and 300 Marines.'
      ]
    },
    {
      position: 'Barracks Manager (Sergeant / E5)',
      timeline: '06/2012 - 07/2014',
      responsibilities: [
        'Created schedules for 150 rotating incoming and outgoing Marines living in the barracks.',
        'Created work orders for any maintenance requests.',
        'Helped create the barracks rules and regulations policy for Bravo Fleet Anti-Terrorism Security Team company.',
        'Ensured rooms were being kept within Marine Corps standards.',
        'Implemented and enforced policies and guidelines.'
      ]
    },
    {
      position: 'Squad Leader (Corporal / E4)',
      timeline: '04/2011 - 06/2012',
      responsibilities: [
        'Supervised Marine Corps infantry and Fleet Anti-Terrorism Security Team tasks applied to the fire team, squad, platoon, and company level.',
        'Ensured the Marines under my charge effectively accomplished all tasks resulting in mission accomplishment, unit readiness, and unit success.',
        'Led and mentored junior Marines to help them grow both personally and professionally.'
      ]
    },
    {
      position: 'Team Leader (Corporal / E4)',
      timeline: '11/2010 - 04/2011',
      responsibilities: [
        'Conducted patrols in Marjah, Helmand Province, Afghanistan.',
        'Provided morale and discipline to the 3 Marines under my charge.',
        'Communicated effectively with individuals in foreign countries using the native language while respecting local culture.',
        'Collaborated with service members from US and foreign military branches in a high-stress environment.',
        'Adapted to the fluid and ever-changing military environment while overseas and stateside.'
      ]
    },
    {
      position: 'Rifleman (Private - Corporal / E1 - E4)',
      timeline: '07/2006 - 11/2010',
      responsibilities: [
        'Accepted and executed any lawful order given to me by my chain of command.',
        'Maintained armed guard positions in foreign countries such as Cuba, Bahrain, and Jordan.'
      ]
    }
  ]
}
